# frozen_string_literal: true

health_problems1 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems2 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems3 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems4 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems5 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems6 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems7 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems8 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems9 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems10 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems11 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems12 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems13 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems14 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems15 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems16 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems17 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems18 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems19 = HealthProblem.create(name: 'disease', degree: rand(1..100))
health_problems20 = HealthProblem.create(name: 'disease', degree: rand(1..100))

Client.create!(name: 'client1', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems1)
Client.create!(name: 'client2', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems2)
Client.create!(name: 'client3', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems3)
Client.create!(name: 'client4', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems4)
Client.create!(name: 'client5', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems5)
Client.create!(name: 'client6', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems6)
Client.create!(name: 'client7', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems7)
Client.create!(name: 'client8', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems8)
Client.create!(name: 'client9', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems9)
Client.create!(name: 'client10', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems10)
Client.create!(name: 'client11', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems11)
Client.create!(name: 'client12', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems12)
Client.create!(name: 'client13', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems13)
Client.create!(name: 'client14', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems14)
Client.create!(name: 'client15', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems15)
Client.create!(name: 'client15', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems16)
Client.create!(name: 'client15', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems17)
Client.create!(name: 'client15', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems18)
Client.create!(name: 'client15', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems19)
Client.create!(name: 'client15', birthdate: Time.now, sex: %w[male female].sample, health_problem: health_problems20)
